'use client';

import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { Check, Clock3, Edit3, LogOut, MapPin, Package, Plus, Save, Trash2, UserRound, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { formatPrice } from '@/lib/currency';

interface CustomerProfileModalProps { onClose: () => void; }
interface Profile { full_name: string; contact_number: string; destination: string; address: string; delivery_notes: string; }
interface SavedAddress extends Profile { id: string; label: string; is_default: boolean; }
interface CustomerOrder { id: string; order_number: string; product_name: string; product_code: string; size: string; quantity: number; unit_price: number; status: string; created_at: string; }
const emptyProfile: Profile = { full_name: '', contact_number: '', destination: '', address: '', delivery_notes: '' };

export function CustomerProfileModal({ onClose }: CustomerProfileModalProps) {
  const [email, setEmail] = useState(''); const [profile, setProfile] = useState<Profile>(emptyProfile); const [addresses, setAddresses] = useState<SavedAddress[]>([]); const [editing, setEditing] = useState<string | null>(null); const [labelName, setLabelName] = useState('Home'); const [orders, setOrders] = useState<CustomerOrder[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');

  useEffect(() => { document.body.style.overflow = 'hidden'; const load = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) { onClose(); return; } setEmail(session.user.email ?? ''); const [{ data: oldProfile }, { data: savedAddresses, error: addressError }, { data: savedOrders, error: ordersError }] = await Promise.all([supabase.from('customer_profiles').select('full_name, contact_number, destination, address, delivery_notes').eq('id', session.user.id).maybeSingle(), supabase.from('customer_addresses').select('id, label, full_name, contact_number, destination, address, delivery_notes, is_default').eq('user_id', session.user.id).order('is_default', { ascending: false }).order('updated_at', { ascending: false }), supabase.from('orders').select('id, order_number, product_name, product_code, size, quantity, unit_price, status, created_at').eq('user_id', session.user.id).order('created_at', { ascending: false })]); if (oldProfile) setProfile({ ...emptyProfile, ...oldProfile }); if (addressError) setError(addressError.message); else setAddresses((savedAddresses ?? []) as SavedAddress[]); if (ordersError) setError(ordersError.message); else setOrders((savedOrders ?? []) as CustomerOrder[]); setLoading(false); }; void load(); return () => { document.body.style.overflow = 'unset'; }; }, [onClose]);
  const update = (key: keyof Profile, value: string) => setProfile(current => ({ ...current, [key]: value }));
  const reset = () => { setEditing(null); setLabelName('Home'); setProfile(emptyProfile); };
  const edit = (item: SavedAddress) => { setEditing(item.id); setLabelName(item.label); setProfile({ full_name: item.full_name, contact_number: item.contact_number, destination: item.destination, address: item.address, delivery_notes: item.delivery_notes }); setMessage(''); setError(''); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); const { data: { session } } = await supabase.auth.getSession(); if (!session) { setError('Your session has expired. Please sign in again.'); setSaving(false); return; } const values = { user_id: session.user.id, label: labelName.trim() || 'Home', ...profile, is_default: addresses.length === 0, updated_at: new Date().toISOString() }; const result = editing ? await supabase.from('customer_addresses').update(values).eq('id', editing).eq('user_id', session.user.id).select('id, label, full_name, contact_number, destination, address, delivery_notes, is_default').single() : await supabase.from('customer_addresses').insert(values).select('id, label, full_name, contact_number, destination, address, delivery_notes, is_default').single(); if (result.error) setError(result.error.message); else { const item = result.data as SavedAddress; setAddresses(current => editing ? current.map(address => address.id === item.id ? item : address) : [...current, item]); setMessage(editing ? 'Address updated.' : 'Address saved.'); reset(); } setSaving(false); };
  const setDefault = async (id: string) => { const { error: saveError } = await supabase.from('customer_addresses').update({ is_default: true }).eq('id', id); if (saveError) setError(saveError.message); else { setAddresses(current => current.map(item => ({ ...item, is_default: item.id === id }))); setMessage('Default address updated.'); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this saved address?')) return; const { error: deleteError } = await supabase.from('customer_addresses').delete().eq('id', id); if (deleteError) setError(deleteError.message); else { setAddresses(current => current.filter(item => item.id !== id)); setMessage('Address deleted.'); if (editing === id) reset(); } };
  const input = 'mt-2 min-h-12 w-full rounded-lg border border-[#D9D3CA] bg-[#FCFBF9] px-3.5 py-3 text-sm text-[#2D2926] outline-none focus:border-[#8C806D] focus:ring-2 focus:ring-[#D9D0C3]/60'; const label = 'block text-[10px] font-bold uppercase tracking-[.14em] text-[#6F6963]';

  return <AnimatePresence><div className="fixed inset-0 z-[80] flex items-end justify-center bg-[#171513]/75 p-0 backdrop-blur-sm sm:items-center sm:p-5"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 18 }} className="flex max-h-[96svh] w-full max-w-6xl flex-col overflow-hidden rounded-t-2xl border border-[#D6CFC7] bg-[#F6F3EE] shadow-2xl sm:max-h-[92svh] sm:rounded-2xl" role="dialog" aria-modal="true" aria-labelledby="profile-title">
    <header className="flex shrink-0 items-center justify-between border-b border-[#DDD7CF] bg-[#FCFBF9] px-5 py-4 sm:px-8 sm:py-5"><div><p className="text-[9px] font-bold uppercase tracking-[.28em] text-[#8C806D]">Above Apprl · Customer profile</p><h2 id="profile-title" className="mt-1 text-lg font-bold uppercase tracking-[.1em] text-[#2D2926]">My account</h2></div><button onClick={onClose} className="rounded-full p-2 text-[#6F6963] hover:bg-[#EEEAE4]" title="Close profile"><X className="h-5 w-5" /></button></header>
    {loading ? <div className="px-5 py-20 text-center text-sm text-[#6F6963]">Loading your profile...</div> : <div className="grid overflow-y-auto lg:grid-cols-[.9fr_1.1fr]">
      <section className="p-5 sm:p-8 lg:border-r lg:border-[#DDD7CF]"><div className="rounded-2xl bg-[#2D2926] p-5 text-[#F8F5EF]"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#D4B483] text-[#2D2926]"><UserRound className="h-5 w-5" /></div><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.2em] text-[#D4B483]">Member account</p><p className="mt-1 truncate text-sm text-white/85">{email}</p></div></div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-white/15 pt-4"><div><p className="text-[9px] uppercase tracking-widest text-white/50">Orders</p><p className="mt-1 text-xl font-semibold">{orders.length}</p></div><div><p className="text-[9px] uppercase tracking-widest text-white/50">Addresses</p><p className="mt-1 text-xl font-semibold">{addresses.length}</p></div></div></div>
        <div className="mt-7 flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-lg bg-[#EEEAE4] p-2"><MapPin className="h-4 w-4 text-[#8C806D]" /></div><div><h3 className="text-xs font-bold uppercase tracking-[.15em] text-[#2D2926]">My addresses</h3><p className="mt-1 text-[11px] text-[#989188]">Save multiple delivery addresses</p></div></div><button type="button" onClick={reset} className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-[#8C806D]"><Plus className="h-4 w-4" /> Add</button></div>
        <div className="mt-4 space-y-3">{addresses.length === 0 ? <div className="rounded-xl border border-dashed border-[#D6CFC7] p-5 text-center text-xs text-[#989188]">No saved addresses yet.</div> : addresses.map(item => <article key={item.id} className={`rounded-xl border p-4 ${item.is_default ? 'border-[#B85D3D] bg-[#FFF9F4]' : 'border-[#DDD7CF] bg-[#FCFBF9]'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold text-[#2D2926]">{item.full_name}</h4><span className="text-xs text-[#989188]">{item.contact_number}</span>{item.is_default && <span className="border border-[#B85D3D] px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider text-[#B85D3D]">Default</span>}</div><p className="mt-2 text-xs leading-5 text-[#6F6963]">{item.address}<br />{item.destination}</p><span className="mt-2 inline-block border border-[#D6CFC7] px-1.5 py-0.5 text-[9px] text-[#8C806D]">{item.label}</span></div><div className="flex shrink-0 gap-1"><button type="button" onClick={() => edit(item)} className="p-1.5 text-[#8C806D] hover:text-[#2D2926]" title="Edit address"><Edit3 className="h-4 w-4" /></button><button type="button" onClick={() => void remove(item.id)} className="p-1.5 text-[#B85D3D]" title="Delete address"><Trash2 className="h-4 w-4" /></button></div></div>{!item.is_default && <button type="button" onClick={() => void setDefault(item.id)} className="mt-3 border border-[#D6CFC7] px-3 py-2 text-[10px] font-semibold text-[#6F6963]">Set as default</button>}</article>)}</div>
        <form onSubmit={save} className="mt-5 rounded-xl border border-[#DDD7CF] bg-[#FCFBF9] p-4"><div className="flex items-center justify-between"><h3 className="text-xs font-bold uppercase tracking-[.14em] text-[#2D2926]">{editing ? 'Edit address' : 'Add new address'}</h3>{editing && <button type="button" onClick={reset} className="text-[10px] font-semibold text-[#8C806D]">Cancel</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className={label}>Address label<input value={labelName} onChange={e => setLabelName(e.target.value)} placeholder="Home, Work, Pickup" className={input} /></label><label className={label}>Full name<input required value={profile.full_name} onChange={e => update('full_name', e.target.value)} className={input} /></label><label className={label}>Contact number<input required type="tel" value={profile.contact_number} onChange={e => update('contact_number', e.target.value)} className={input} /></label><label className={label}>Destination / city<input required value={profile.destination} onChange={e => update('destination', e.target.value)} className={input} /></label><label className="block text-[10px] font-bold uppercase tracking-[.14em] text-[#6F6963] sm:col-span-2">Complete address<textarea required rows={2} value={profile.address} onChange={e => update('address', e.target.value)} className={input} /></label><label className="block text-[10px] font-bold uppercase tracking-[.14em] text-[#6F6963] sm:col-span-2">Delivery notes <span className="font-normal normal-case tracking-normal">(optional)</span><textarea rows={2} value={profile.delivery_notes} onChange={e => update('delivery_notes', e.target.value)} className={input} /></label></div>{error && <p className="mt-3 rounded-lg border border-[#E5BDB0] bg-[#FFF5F1] p-3 text-xs text-[#9A4D3A]">{error}</p>}{message && <p className="mt-3 rounded-lg border border-[#CFDCC8] bg-[#F0F5ED] p-3 text-xs text-[#4D633E]">{message}</p>}<button disabled={saving} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#2D2926] px-5 text-xs font-bold uppercase tracking-[.16em] text-[#F4F1EE] disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Saving...' : editing ? 'Save changes' : 'Save address'}</button></form><button onClick={async () => { await supabase.auth.signOut(); onClose(); }} className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#B85D3D]"><LogOut className="h-4 w-4" /> Sign out</button>
      </section>
      <section className="border-t border-[#DDD7CF] p-5 sm:p-8 lg:border-t-0"><div className="mb-5 flex items-end justify-between border-b border-[#DDD7CF] pb-5"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#8C806D]">Your activity</p><div className="mt-2 flex items-center gap-2"><Package className="h-4 w-4 text-[#8C806D]" /><h3 className="text-lg font-semibold text-[#2D2926]">Order history</h3></div></div><span className="rounded-full bg-[#EEEAE4] px-3 py-1 text-[10px] font-bold text-[#6F6963]">{orders.length} order{orders.length === 1 ? '' : 's'}</span></div>{orders.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-[#D6CFC7] text-center"><Package className="h-8 w-8 text-[#C6BFB4]" /><p className="mt-4 text-sm font-semibold uppercase tracking-wider text-[#6F6963]">No orders yet</p><p className="mt-1 text-xs text-[#989188]">Your orders will appear here after checkout.</p></div> : <div className="space-y-3">{orders.map(order => <article key={order.id} className="rounded-2xl border border-[#DDD7CF] bg-[#FCFBF9] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#8C806D]">{order.order_number}</p><h4 className="mt-1 text-sm font-bold uppercase tracking-wide text-[#2D2926]">{order.product_name}</h4><p className="mt-1 text-xs text-[#77716A]">{order.product_code} · Size {order.size} · Qty {order.quantity}</p></div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider ${statusClass(order.status)}`}>{order.status === 'delivered' ? <Check className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}{order.status}</span></div><div className="mt-4 flex items-center justify-between border-t border-[#E8E3DB] pt-3 text-xs"><span className="text-[#989188]">{new Date(order.created_at).toLocaleDateString('en-PH', { year: 'numeric', month: 'short', day: 'numeric' })}</span><strong className="text-base text-[#2D2926]">{formatPrice(Number(order.unit_price) * order.quantity)}</strong></div></article>)}</div>}</section>
    </div>}
  </motion.div></div></AnimatePresence>;
}
function statusClass(status: string) { return status === 'delivered' ? 'bg-[#E8EFE4] text-[#56704B]' : status === 'cancelled' ? 'bg-[#FFF1ED] text-[#9A4D3A]' : 'bg-[#F2EEE6] text-[#8C806D]'; }
