'use client';

import Link from 'next/link';
import { AlertTriangle, ArrowUpRight, BarChart3, Box, CheckCircle2, CircleDollarSign, Layers3, Package, Tag } from 'lucide-react';
import { useAdmin } from '@/context/AdminContext';

function QuickStat({ label, value, icon: Icon, dark = false }: { label: string; value: string | number; icon: React.ElementType; dark?: boolean }) {
  return <div className={`rounded-2xl border p-4 ${dark ? 'border-[#20242b] bg-[#20242b] text-white' : 'border-[#e0e1dc] bg-white text-[#24272b]'}`}><div className="flex items-center justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-full ${dark ? 'bg-white/10' : 'bg-[#f1f2ed]'}`}><Icon className={`h-4 w-4 ${dark ? 'text-white' : 'text-[#74784f]'}`} strokeWidth={1.7} /></div><span className={`text-[10px] ${dark ? 'text-[#aeb2ad]' : 'text-[#929695]'}`}>Live</span></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-[11px] ${dark ? 'text-[#b9bdb8]' : 'text-[#85898a]'}`}>{label}</p></div>;
}

export function AdminDashboard() {
  const { products, categories } = useAdmin();
  const active = products.filter(p => p.stockCount > 0).length;
  const outOfStock = products.filter(p => p.stockCount === 0).length;
  const lowStock = products.filter(p => p.stockCount > 0 && p.stockCount <= 5).length;
  const totalUnits = products.reduce((sum, p) => sum + p.stockCount, 0);
  const inventoryValue = products.reduce((sum, p) => sum + p.price * p.stockCount, 0);
  const categoryStats = categories.map(c => ({ ...c, count: products.filter(p => p.category === c.id).length })).sort((a, b) => b.count - a.count);
  const maxCategoryCount = Math.max(1, ...categoryStats.map(c => c.count));
  const attentionProducts = products.filter(p => p.stockCount <= 5).slice(0, 4);
  const recentProducts = products.slice(0, 6);

  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><QuickStat label="Total products" value={products.length} icon={Package} /><QuickStat label="Active products" value={active} icon={CheckCircle2} dark /><QuickStat label="Inventory units" value={totalUnits.toLocaleString()} icon={Box} /><QuickStat label="Categories" value={categories.length} icon={Tag} /><QuickStat label="Low stock" value={lowStock} icon={AlertTriangle} /><QuickStat label="Inventory value" value={`$${inventoryValue.toLocaleString('en-US', { maximumFractionDigits: 0 })}`} icon={CircleDollarSign} /></div>

    <div className="grid gap-5 xl:grid-cols-[1.45fr_0.85fr]">
      <section className="rounded-2xl border border-[#e0e1dc] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Statistics</h2><p className="mt-1 text-xs text-[#85898a]">Products distributed across your collections</p></div><div className="flex items-center gap-3 text-[11px] text-[#85898a]"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#20242b]" /> Products</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#c7c9c3]" /> Inventory units</span></div></div><div className="mt-8 flex h-52 items-end gap-2 border-b border-[#e7e8e2] px-2 sm:gap-4">{categoryStats.slice(0, 8).map(c => <div key={c.id} className="flex h-full flex-1 items-end gap-1.5"><div className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-[#20242b] transition-all hover:bg-[#74784f]" style={{ height: `${Math.max(c.count ? 12 : 3, c.count / maxCategoryCount * 100)}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 rounded bg-[#20242b] px-2 py-1 text-[10px] text-white group-hover:block">{c.count}</span></div></div><div className="hidden h-full flex-1 items-end sm:flex"><div className="w-full rounded-t-md bg-[#c7c9c3]" style={{ height: `${Math.max(c.count ? 9 : 3, Math.min(100, (products.filter(p => p.category === c.id).reduce((s, p) => s + p.stockCount, 0) / Math.max(1, totalUnits)) * 100 * 2))}%` }} /></div></div>)}</div><div className="mt-3 flex gap-2 overflow-hidden px-2">{categoryStats.slice(0, 8).map(c => <span key={c.id} className="min-w-0 flex-1 truncate text-center text-[9px] text-[#85898a]">{c.label.replace('UA ', '').replace('ua ', '')}</span>)}</div></section>
      <section className="rounded-2xl border border-[#e0e1dc] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Needs attention</h2><p className="mt-1 text-xs text-[#85898a]">Products that need inventory review</p></div><AlertTriangle className="h-5 w-5 text-[#b56b4d]" strokeWidth={1.6} /></div><div className="mt-6 space-y-4">{attentionProducts.map(p => <div key={p.id} className="flex items-center gap-3"><img src={p.frontImage} alt="" className="h-10 w-9 rounded-md object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{p.name}</p><p className="mt-1 text-[11px] text-[#85898a]">{p.stockCount === 0 ? 'Out of stock' : `${p.stockCount} remaining`}</p></div><span className="rounded-full bg-[#f4e4de] px-2 py-1 text-[10px] font-semibold text-[#a5523b]">Review</span></div>)}{attentionProducts.length === 0 && <div className="py-8 text-center text-sm text-[#85898a]">All inventory levels look healthy.</div>}</div><Link href="/admin/products" className="mt-6 flex items-center justify-center gap-1 rounded-lg border border-[#dfe0da] py-2.5 text-xs font-semibold text-[#626741] hover:bg-[#f2f3ed]">Manage inventory <ArrowUpRight className="h-3.5 w-3.5" /></Link></section>
    </div>

    <section className="overflow-hidden rounded-2xl border border-[#e0e1dc] bg-white"><div className="flex items-center justify-between border-b border-[#e8e9e4] px-5 py-5 sm:px-6"><div><h2 className="text-lg font-semibold">Manage products</h2><p className="mt-1 text-xs text-[#85898a]">Recently added products in your catalog</p></div><Link href="/admin/products" className="rounded-lg bg-[#20242b] px-3.5 py-2 text-xs font-semibold text-white hover:bg-[#74784f]">View all <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-b border-[#ededE8] bg-[#fbfbf8]"><tr>{['Product','Category','Price','Stock','Status'].map(h => <th key={h} className="px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-[#85898a]">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#f0f0eb]">{recentProducts.map(p => <tr key={p.id} className="hover:bg-[#fbfbf8]"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><img src={p.frontImage} alt="" className="h-10 w-8 rounded-md object-cover" /><div><p className="text-sm font-medium">{p.name}</p><p className="mt-1 text-[11px] text-[#85898a]">SKU: {p.code}</p></div></div></td><td className="px-5 py-3.5 text-sm text-[#62676a]">{categories.find(c => c.id === p.category)?.label ?? p.category}</td><td className="px-5 py-3.5 text-sm font-semibold">{p.currency}{p.price.toFixed(2)}</td><td className="px-5 py-3.5 text-sm">{p.stockCount}</td><td className="px-5 py-3.5"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${p.stockCount ? 'bg-[#e7eadb] text-[#58603c]' : 'bg-[#f5e2dc] text-[#a5523b]'}`}>{p.stockCount ? 'Active' : 'Out of stock'}</span></td></tr>)}{recentProducts.length === 0 && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-[#85898a]">No products have been added yet.</td></tr>}</tbody></table></div></section>
  </div>;
}
